# Pandas Data Cleaning & Transformations – Customers & Sales

This notebook focuses on **data cleaning and transformation techniques** using Pandas with real-time **Customers & Sales CSV data**.

## Load Data

In [18]:
import pandas as pd

customers = pd.read_csv('customersinfo.csv')
sales = pd.read_csv('salesinfo.csv')

customers, sales

(   CustomerID CustomerName       City   Age
 0         101          Raj  Hyderabad  28.0
 1         102        Anita  Bangalore  35.0
 2         103         John    Chennai  42.0
 3         104        Meera  Hyderabad   NaN
 4         105        David     Mumbai  38.0
 5         105        David     Mumbai  38.0
 6         102        Anita  Bangalore  35.0,
    OrderID  CustomerID Product  Amount
 0     1001         101  Laptop   55000
 1     1002         102  Mobile   18000
 2     1003         101  Tablet   22000
 3     1004         104  Laptop   60000
 4     1005         105  Mobile   20000)

## Data Cleaning – Missing Values
Check and handle missing values.

In [19]:
customers.isnull().sum()

#sales.isnull().sum()

CustomerID      0
CustomerName    0
City            0
Age             1
dtype: int64

In [27]:
# Fill missing ages with average age
customers['Age'] = customers['Age'].fillna(customers['Age'].mean())
customers

   CustomerID CustomerName       City   Age
0         101          Raj  Hyderabad  28.0
1         102        Anita  Bangalore  35.0
2         103         John    Chennai  42.0
3         104        Meera  Hyderabad  36.0
4         105        David     Mumbai  38.0

## Remove Duplicates
Identify and remove duplicate records.

In [21]:
customers

   CustomerID CustomerName       City   Age
0         101          Raj  Hyderabad  28.0
1         102        Anita  Bangalore  35.0
2         103         John    Chennai  42.0
3         104        Meera  Hyderabad  36.0
4         105        David     Mumbai  38.0
5         105        David     Mumbai  38.0
6         102        Anita  Bangalore  35.0

In [22]:
customers.duplicated().sum()

np.int64(2)

In [23]:
customers = customers.drop_duplicates()
customers

   CustomerID CustomerName       City   Age
0         101          Raj  Hyderabad  28.0
1         102        Anita  Bangalore  35.0
2         103         John    Chennai  42.0
3         104        Meera  Hyderabad  36.0
4         105        David     Mumbai  38.0

In [24]:
customers.duplicated().sum()

np.int64(0)

## Data Type Corrections
Ensure correct data types.

In [25]:
sales.dtypes

sales['Amount'] = sales['Amount'].astype(float)

## Column Transformations
Create new calculated columns.

In [26]:
# Add Discounted Amount (10%)
sales['DiscountedAmount'] = sales['Amount'] * 0.90
sales

   OrderID  CustomerID Product   Amount  DiscountedAmount
0     1001         101  Laptop  55000.0           49500.0
1     1002         102  Mobile  18000.0           16200.0
2     1003         101  Tablet  22000.0           19800.0
3     1004         104  Laptop  60000.0           54000.0
4     1005         105  Mobile  20000.0           18000.0

## Rename & Reorder Columns

In [31]:
#sales = sales.rename(columns={'Amount': 'OriginalAmount'})
sales = sales[['OrderID', 'Product','CustomerID','OriginalAmount','DiscountedAmount']]
sales

   OrderID Product  CustomerID  OriginalAmount  DiscountedAmount
0     1001  Laptop         101         55000.0           49500.0
1     1002  Mobile         102         18000.0           16200.0
2     1003  Tablet         101         22000.0           19800.0
3     1004  Laptop         104         60000.0           54000.0
4     1005  Mobile         105         20000.0           18000.0

## Merge Cleaned Data

In [33]:
final_df = pd.merge(customers, sales, on='CustomerID')
final_df

,CustomerID,CustomerName,City,Age,OrderID,Product,OriginalAmount,DiscountedAmount
0,101,Raj,Hyderabad,28.0,1001,Laptop,55000.0,49500.0
1,101,Raj,Hyderabad,28.0,1003,Tablet,22000.0,19800.0
2,105,David,Mumbai,38.0,1005,Mobile,20000.0,18000.0
3,102,Anita,Bangalore,35.0,1002,Mobile,18000.0,16200.0
4,104,Meera,Hyderabad,36.0,1004,Laptop,60000.0,54000.0

## Outlier Detection
Identify high-value sales outliers.

In [36]:
final_df=final_df[final_df['OriginalAmount'] > 50000]

## Export Cleaned Data

In [40]:
final_df.to_csv('cleaned_customers_sales_1.csv',index=False)
final_df.head()

,CustomerID,CustomerName,City,Age,OrderID,Product,OriginalAmount,DiscountedAmount
0,101,Raj,Hyderabad,28.0,1001,Laptop,55000.0,49500.0
4,104,Meera,Hyderabad,36.0,1004,Laptop,60000.0,54000.0

In [41]:
customers_df = pd.read_csv('cleaned_customers_sales_1.csv')
customers_df.head()

,CustomerID,CustomerName,City,Age,OrderID,Product,OriginalAmount,DiscountedAmount
0,101,Raj,Hyderabad,28.0,1001,Laptop,55000.0,49500.0
1,104,Meera,Hyderabad,36.0,1004,Laptop,60000.0,54000.0

## Pandas Cleaning Methods Covered
- isnull(), fillna()
- duplicated(), drop_duplicates()
- astype()
- rename()
- merge()
- Export cleaned data