# Pandas Module – What, Why & Hands-on Exercises

## What is Pandas?
Pandas is a powerful Python library used for data manipulation and analysis. It provides fast, flexible data structures like **Series** and **DataFrame**.

## Why Pandas?
- Easy CSV/Excel handling
- Data cleaning and transformation
- Powerful filtering, grouping, aggregation
- Widely used in Data Analytics, Data Science, ML

In [ ]:
!pip install pandas

In [1]:
import pandas as pd

customers = pd.read_csv('customers.csv')
sales = pd.read_csv('sales.csv')

customers, sales

(   CustomerID CustomerName       City  Age
 0         101          Raj  Hyderabad   28
 1         102        Anita  Bangalore   35
 2         103         John    Chennai   42
 3         104        Meera  Hyderabad   30
 4         105        David     Mumbai   38,
    OrderID  CustomerID Product  Amount
 0     1001         101  Laptop   55000
 1     1002         102  Mobile   18000
 2     1003         101  Tablet   22000
 3     1004         104  Laptop   60000
 4     1005         105  Mobile   20000)

##  Basic Data Exploration
- Display first 3 rows
- Check shape and column names

In [5]:
#customers.head(3)

#customers.shape

customers.columns

Index(['CustomerID', 'CustomerName', 'City', 'Age'], dtype='str')

##  Filtering Customers
Find customers from Hyderabad.

In [9]:
customers[customers['age'] == 'Hyderabad']

KeyError: 'city'

##  High-Value Sales
Filter orders where Amount > 20000.

In [7]:
sales[sales['Amount'] > 20000]

   OrderID  CustomerID Product  Amount
0     1001         101  Laptop   55000
2     1003         101  Tablet   22000
3     1004         104  Laptop   60000

## GroupBy Analysis
Calculate total sales per customer.

In [10]:
sales.groupby('Product')['Amount'].sum()

Product
Laptop    115000
Mobile     38000
Tablet     22000
Name: Amount, dtype: int64

## Merge Customers & Sales
Join customer details with sales data.

In [11]:
merged_df = pd.merge(customers, sales, on='CustomerID')
merged_df

   CustomerID CustomerName       City  Age  OrderID Product  Amount
0         101          Raj  Hyderabad   28     1001  Laptop   55000
1         101          Raj  Hyderabad   28     1003  Tablet   22000
2         105        David     Mumbai   38     1005  Mobile   20000
3         102        Anita  Bangalore   35     1002  Mobile   18000
4         104        Meera  Hyderabad   30     1004  Laptop   60000

##  Sales Summary
- Total sales
- Average order value

In [12]:
total_sales = sales['Amount'].sum()
avg_order = sales['Amount'].mean()

total_sales, avg_order

(np.int64(175000), np.float64(35000.0))

## Key Pandas Methods Used
- read_csv()
- head(), shape, columns
- Boolean filtering
- groupby()
- merge()
- sum(), mean()