# ETL  Project (Pandas + MySQL)

This project demonstrates a **real-world ETL pipeline** using Pandas and MySQL.

**Use case:** Sales data ingestion, cleaning, transformation, and loading into MySQL.

1️⃣ Project Architecture

Source → Transform → Target

ETL flow diagram explained in text

2️⃣ Extract

Generate & read sales CSV

Simulates real incoming data

3️⃣ Transform

Add calculated column (total_amount)

Remove duplicates

Type casting

Business aggregations

4️⃣ Load

Load clean data into MySQL:

sales_fact table

sales_summary table

Uses SQLAlchemy (best practice)

5️⃣ Validate & Analyze

Verify loaded data

Revenue analysis per product

## 1. Project Architecture


**Source:** CSV file (Sales data)  
**Transform:** Data cleaning, type casting, aggregations  
**Target:** MySQL Database  

ETL Flow:
CSV → Pandas → Transform → MySQL → Analytics

## 2. Install Required Libraries

In [ ]:
!pip install pandas mysql-connector-python sqlalchemy

## 3. Create Sample Sales CSV

In [1]:

import pandas as pd

data = {
    "order_id": [101, 102, 103, 104, 105,101],
    "customer": ["Ravi", "Amit", "Neha", "Ravi", "Amit","Ravi"],
    "product": ["Laptop", "Mouse", "Keyboard", "Laptop", "Mouse","Laptop"],
    "quantity": [1, 2, 1, 1, 3,1],
    "price": [60000, 500, 1500, 60000, 500,60000]
}

df_sales = pd.DataFrame(data)
df_sales.to_csv("sales_data.csv", index=False)
df_sales

   order_id customer   product  quantity  price
0       101     Ravi    Laptop         1  60000
1       102     Amit     Mouse         2    500
2       103     Neha  Keyboard         1   1500
3       104     Ravi    Laptop         1  60000
4       105     Amit     Mouse         3    500
5       101     Ravi    Laptop         1  60000

## 4. Extract: Read CSV

In [2]:

df = pd.read_csv("sales_data.csv")
df

   order_id customer   product  quantity  price
0       101     Ravi    Laptop         1  60000
1       102     Amit     Mouse         2    500
2       103     Neha  Keyboard         1   1500
3       104     Ravi    Laptop         1  60000
4       105     Amit     Mouse         3    500
5       101     Ravi    Laptop         1  60000

## 5. Transform: Data Cleaning & Enrichment

In [3]:

# Add total_amount column
df["total_amount"] = df["quantity"] * df["price"]

# Remove duplicates (if any)
df = df.drop_duplicates()

# Type conversion
df["order_id"] = df["order_id"].astype(int)

df

   order_id customer   product  quantity  price  total_amount
0       101     Ravi    Laptop         1  60000         60000
1       102     Amit     Mouse         2    500          1000
2       103     Neha  Keyboard         1   1500          1500
3       104     Ravi    Laptop         1  60000         60000
4       105     Amit     Mouse         3    500          1500

## 6. Transform: Business Aggregations

In [4]:

sales_summary = df.groupby("product")["total_amount"].sum().reset_index()
sales_summary

    product  total_amount
0  Keyboard          1500
1    Laptop        120000
2     Mouse          2500

## 7. Load: Connect to MySQL

In [5]:

from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:mysql@localhost:3306/hr"
)

engine

Engine(mysql+mysqlconnector://root:***@localhost:3306/hr)

## 8. Load: Store Clean Data into MySQL

In [6]:

df.to_sql(
    name="sales_fact",
    con=engine,
    if_exists="replace",
    index=False
)

sales_summary.to_sql(
    name="sales_summary",
    con=engine,
    if_exists="replace",
    index=False
)

print("ETL Load Completed")

ETL Load Completed

## 9. Validate Load

In [7]:

pd.read_sql("SELECT * FROM sales_fact", con=engine)

   order_id customer   product  quantity  price  total_amount
0       101     Ravi    Laptop         1  60000         60000
1       102     Amit     Mouse         2    500          1000
2       103     Neha  Keyboard         1   1500          1500
3       104     Ravi    Laptop         1  60000         60000
4       105     Amit     Mouse         3    500          1500

In [8]:
pd.read_sql("SELECT * FROM sales_summary", con=engine)

    product  total_amount
0  Keyboard          1500
1    Laptop        120000
2     Mouse          2500

## 10. Analytics Query

In [9]:

pd.read_sql(
    "SELECT product, SUM(total_amount) AS revenue FROM sales_fact GROUP BY product",
    con=engine
)

    product   revenue
0    Laptop  120000.0
1     Mouse    2500.0
2  Keyboard    1500.0

## 11. Project Outcome


✔ Built a real-time ETL pipeline  
✔ Cleaned & transformed raw data  
✔ Loaded fact and summary tables  
✔ Ready for dashboards / BI tools